---
title: PC Review
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: person@example.com
description: Welcome to my new blog running on Jekyll and NorthStack!
baseurl: ''
url: ''
markdown: kramdown
