# General Settings
title: PC Review
email: person@example.com
description: "Welcome to my new blog running on Jekyll and NorthStack!"
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
