---
title: PC Review
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
email: 
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: sunrise
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.16.5
repository: chrisbg69.github.io
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- _assets
- gulpfile.js
- package.json
- package-lock.json
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: First Lastname
  avatar: "/assets/images/bio-photo.jpg"
  bio: My awesome biography constrained to a sentence or two goes here.
  links:
  - label: Website
    icon: fas fa-fw fa-link
    url: https://
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/
  - label: Instagram
    icon: fab fa-fw fa-instagram
    url: https://instagram.com/
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
github:
- metadata
