---
title: PC Review
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: archangelbg@abv.bg
description: Welcome to my new blog running on Jekyll
permalink: /:categories/:title/
baseurl: ''
url: ''
markdown: kramdown

plugins: [jekyll-paginate]

paginate: 3
paginate_path: /blog/page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site  
  - gulpfile.js
  - package.json
  - package-lock.json

